//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiritori.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isWindowShadow {
            get {
                return ((bool)(this["isWindowShadow"]));
            }
            set {
                this["isWindowShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isAfloatWindow {
            get {
                return ((bool)(this["isAfloatWindow"]));
            }
            set {
                this["isAfloatWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WindowAlphaPercent {
            get {
                return ((int)(this["WindowAlphaPercent"]));
            }
            set {
                this["WindowAlphaPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isStartup {
            get {
                return ((bool)(this["isStartup"]));
            }
            set {
                this["isStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int HistoryLimit {
            get {
                return ((int)(this["HistoryLimit"]));
            }
            set {
                this["HistoryLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isFirstRunShown {
            get {
                return ((bool)(this["isFirstRunShown"]));
            }
            set {
                this["isFirstRunShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isOpenMenuOnAppStart {
            get {
                return ((bool)(this["isOpenMenuOnAppStart"]));
            }
            set {
                this["isOpenMenuOnAppStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isOverlay {
            get {
                return ((bool)(this["isOverlay"]));
            }
            set {
                this["isOverlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isScreenGuide {
            get {
                return ((bool)(this["isScreenGuide"]));
            }
            set {
                this["isScreenGuide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isHighlightWindowOnHover {
            get {
                return ((bool)(this["isHighlightWindowOnHover"]));
            }
            set {
                this["isHighlightWindowOnHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color HoverHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["HoverHighlightColor"]));
            }
            set {
                this["HoverHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int HoverHighlightAlphaPercent {
            get {
                return ((int)(this["HoverHighlightAlphaPercent"]));
            }
            set {
                this["HoverHighlightAlphaPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int HoverHighlightThickness {
            get {
                return ((int)(this["HoverHighlightThickness"]));
            }
            set {
                this["HoverHighlightThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color CaptureBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CaptureBackgroundColor"]));
            }
            set {
                this["CaptureBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int CaptureBackgroundAlphaPercent {
            get {
                return ((int)(this["CaptureBackgroundAlphaPercent"]));
            }
            set {
                this["CaptureBackgroundAlphaPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isScreenSnap {
            get {
                return ((bool)(this["isScreenSnap"]));
            }
            set {
                this["isScreenSnap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isPlaySound {
            get {
                return ((bool)(this["isPlaySound"]));
            }
            set {
                this["isPlaySound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isShowNotify {
            get {
                return ((bool)(this["isShowNotify"]));
            }
            set {
                this["isShowNotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string UICulture {
            get {
                return ((string)(this["UICulture"]));
            }
            set {
                this["UICulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Shift+5")]
        public string HotkeyCapture {
            get {
                return ((string)(this["HotkeyCapture"]));
            }
            set {
                this["HotkeyCapture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Shift+4")]
        public string HotkeyOcr {
            get {
                return ((string)(this["HotkeyOcr"]));
            }
            set {
                this["HotkeyOcr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowNotifyOCR {
            get {
                return ((bool)(this["isShowNotifyOCR"]));
            }
            set {
                this["isShowNotifyOCR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Shift+6")]
        public string HotkeyLive {
            get {
                return ((string)(this["HotkeyLive"]));
            }
            set {
                this["HotkeyLive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int LivePreviewMaxFps {
            get {
                return ((int)(this["LivePreviewMaxFps"]));
            }
            set {
                this["LivePreviewMaxFps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magnifier")]
        public string LivePreviewBackend {
            get {
                return ((string)(this["LivePreviewBackend"]));
            }
            set {
                this["LivePreviewBackend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MagnifierMouseThrough {
            get {
                return ((bool)(this["MagnifierMouseThrough"]));
            }
            set {
                this["MagnifierMouseThrough"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MagnifierNoActivate {
            get {
                return ((bool)(this["MagnifierNoActivate"]));
            }
            set {
                this["MagnifierNoActivate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmoothZoomEnabled {
            get {
                return ((bool)(this["SmoothZoomEnabled"]));
            }
            set {
                this["SmoothZoomEnabled"] = value;
            }
        }
    }
}
