//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiritori.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiritori.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Kiritori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Always on top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Menu.AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Capture {
            get {
                return ResourceManager.GetString("Menu.Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_CloseWindow {
            get {
                return ResourceManager.GetString("Menu.CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut(copy and close) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Drop Shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_DropShadow {
            get {
                return ResourceManager.GetString("Menu.DropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Paint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_EditPaint {
            get {
                return ResourceManager.GetString("Menu.EditPaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit Kiritori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Minimize {
            get {
                return ResourceManager.GetString("Menu.Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Opacity {
            get {
                return ResourceManager.GetString("Menu.Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_OpenImage {
            get {
                return ResourceManager.GetString("Menu.OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_OriginalSize {
            get {
                return ResourceManager.GetString("Menu.OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MainMenu / Preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Preferences {
            get {
                return ResourceManager.GetString("Menu.Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Print {
            get {
                return ResourceManager.GetString("Menu.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_SaveImage {
            get {
                return ResourceManager.GetString("Menu.SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size 10% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Size10 {
            get {
                return ResourceManager.GetString("Menu.Size10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size 100% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Size100 {
            get {
                return ResourceManager.GetString("Menu.Size100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size 150% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Size150 {
            get {
                return ResourceManager.GetString("Menu.Size150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size 200% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Size200 {
            get {
                return ResourceManager.GetString("Menu.Size200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size 50% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Size50 {
            get {
                return ResourceManager.GetString("Menu.Size50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size 500% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Size500 {
            get {
                return ResourceManager.GetString("Menu.Size500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Window {
            get {
                return ResourceManager.GetString("Menu.Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom(%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Zoom {
            get {
                return ResourceManager.GetString("Menu.Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom In(+10%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_ZoomIn {
            get {
                return ResourceManager.GetString("Menu.ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Out(-10%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_ZoomOut {
            get {
                return ResourceManager.GetString("Menu.ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefForm_Title {
            get {
                return ResourceManager.GetString("PrefForm.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tab_Advanced {
            get {
                return ResourceManager.GetString("Tab.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Appearance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tab_Appearance {
            get {
                return ResourceManager.GetString("Tab.Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genral に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tab_General {
            get {
                return ResourceManager.GetString("Tab.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tab_Info {
            get {
                return ResourceManager.GetString("Tab.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tab_Shortcut {
            get {
                return ResourceManager.GetString("Tab.Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always on top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Text.AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   and more. See Shortcuts tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_AndMore {
            get {
                return ResourceManager.GetString("Text.AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_AppSetting {
            get {
                return ResourceManager.GetString("Text.AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Background {
            get {
                return ResourceManager.GetString("Text.Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_BtnCancel {
            get {
                return ResourceManager.GetString("Text.BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit Kiritori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_BtnExit {
            get {
                return ResourceManager.GetString("Text.BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_BtnSave {
            get {
                return ResourceManager.GetString("Text.BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Startup folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_BtnStartupFolder {
            get {
                return ResourceManager.GetString("Text.BtnStartupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Startup Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_BtnStartupSetting {
            get {
                return ResourceManager.GetString("Text.BtnStartupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Settings(press key duaring capture) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CaptureOptionSetting {
            get {
                return ResourceManager.GetString("Text.CaptureOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CaptureSetting {
            get {
                return ResourceManager.GetString("Text.CaptureSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Close {
            get {
                return ResourceManager.GetString("Text.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close All Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CloseAllWindows {
            get {
                return ResourceManager.GetString("Text.CloseAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CloseWindow {
            get {
                return ResourceManager.GetString("Text.CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit the application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ConfirmExit {
            get {
                return ResourceManager.GetString("Text.ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Exit Kiritori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ConfirmExitTitle {
            get {
                return ResourceManager.GetString("Text.ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Copy {
            get {
                return ResourceManager.GetString("Text.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CopyToClipboard {
            get {
                return ResourceManager.GetString("Text.CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_DropShadow {
            get {
                return ResourceManager.GetString("Text.DropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide All Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_HideAllWindows {
            get {
                return ResourceManager.GetString("Text.HideAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highlight color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_HighlightColor {
            get {
                return ResourceManager.GetString("Text.HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highlight on hover に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_HighlightOnHover {
            get {
                return ResourceManager.GetString("Text.HighlightOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highlignt thickness(px) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_HighlightThickness {
            get {
                return ResourceManager.GetString("Text.HighlightThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_History {
            get {
                return ResourceManager.GetString("Text.History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_HistoryLimit {
            get {
                return ResourceManager.GetString("Text.HistoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hotkeys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Hotkeys {
            get {
                return ResourceManager.GetString("Text.Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ImageCapture {
            get {
                return ResourceManager.GetString("Text.ImageCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Language {
            get {
                return ResourceManager.GetString("Text.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MainMenu / Preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_MainPreferences {
            get {
                return ResourceManager.GetString("Text.MainPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Minimize {
            get {
                return ResourceManager.GetString("Text.Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Move {
            get {
                return ResourceManager.GetString("Text.Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify in tray on capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_NotifyTray {
            get {
                return ResourceManager.GetString("Text.NotifyTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Image File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_OpenImageFile {
            get {
                return ResourceManager.GetString("Text.OpenImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Option {
            get {
                return ResourceManager.GetString("Text.Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound on capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PlaySound {
            get {
                return ResourceManager.GetString("Text.PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture at previous region に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PreviousCapture {
            get {
                return ResourceManager.GetString("Text.PreviousCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Print {
            get {
                return ResourceManager.GetString("Text.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run at Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Runatstartup {
            get {
                return ResourceManager.GetString("Text.Runatstartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Save {
            get {
                return ResourceManager.GetString("Text.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_SaveImage {
            get {
                return ResourceManager.GetString("Text.SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show All Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ShowAllWindows {
            get {
                return ResourceManager.GetString("Text.ShowAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show guide lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ShowGuide {
            get {
                return ResourceManager.GetString("Text.ShowGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t show this Menu at startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ShowScreen {
            get {
                return ResourceManager.GetString("Text.ShowScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Snap {
            get {
                return ResourceManager.GetString("Text.Snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Square crop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_SquareCrop {
            get {
                return ResourceManager.GetString("Text.SquareCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_StartCapture {
            get {
                return ResourceManager.GetString("Text.StartCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Startup {
            get {
                return ResourceManager.GetString("Text.Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup is managed by Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_StartupManaged {
            get {
                return ResourceManager.GetString("Text.StartupManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings &gt; Apps &gt; Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_StartupManagedTip {
            get {
                return ResourceManager.GetString("Text.StartupManagedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tip: It minimizes to the taskbar. Right-clicking the icon displays a menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_TipTasktray {
            get {
                return ResourceManager.GetString("Text.TipTasktray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle guide lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ToggleGuide {
            get {
                return ResourceManager.GetString("Text.ToggleGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to update startup setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_UnableSetStartup {
            get {
                return ResourceManager.GetString("Text.UnableSetStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video Capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_VideoCapture {
            get {
                return ResourceManager.GetString("Text.VideoCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What Kiritori does に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_WhatIs1 {
            get {
                return ResourceManager.GetString("Text.WhatIs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   • Capture any screen region instantly\n• Shows as a borderless, always-on-top window\n• Move, zoom, copy, or save the cutout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_WhatIs2 {
            get {
                return ResourceManager.GetString("Text.WhatIs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_WindowOpacity {
            get {
                return ResourceManager.GetString("Text.WindowOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Operations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_WindowOperation {
            get {
                return ResourceManager.GetString("Text.WindowOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_WindowSetting {
            get {
                return ResourceManager.GetString("Text.WindowSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ZoomIn {
            get {
                return ResourceManager.GetString("Text.ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ZoomOut {
            get {
                return ResourceManager.GetString("Text.ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ZoomReset {
            get {
                return ResourceManager.GetString("Text.ZoomReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kiritori - minimized to tray (click to open) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tray_TrayIcon {
            get {
                return ResourceManager.GetString("Tray.TrayIcon", resourceCulture);
            }
        }
    }
}
