<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Kiritori.LiveCaptureBenchmarks</AssemblyName>
    <RootNamespace>Kiritori.LiveCaptureBenchmarks</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Kiritori\Kiritori.csproj" />
  </ItemGroup>
</Project>
